# Generated by Django 6.0 on 2025-12-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reallyuser',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='reallyuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
