# Generated by Django 6.0 on 2025-12-17 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_reallyuser_avatar_alter_reallyuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('in', 'In stock'), ('out', 'Out of stock')], default='in', max_length=30),
        ),
    ]
