# Generated by Django 6.0 on 2025-12-17 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_post_image_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель интернета'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(default='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='Имя', max_length=120),
        ),
    ]
